Correct types for infile, outfile
(We can ignore the "unused var" problems.)

$ make cocasm
gcc -Wall -Werror -o cocasm ocasm.c
ocasm.c:107:11: error: unused variable 'infile' [-Werror,-Wunused-variable]
    FILE *infile = fopen(argv[1],"r"); /* Open the input file */
          ^
ocasm.c:108:11: error: unused variable 'outfile' [-Werror,-Wunused-variable]
    FILE *outfile = fopen("out.oca","w"); /* Open the output file */
          ^
2 errors generated.
make: *** [cocasm] Error 1